CREATE DATABASE XCHANGE;

USE xchange;

CREATE TABLE users (
  user_id INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  last_name VARCHAR(50) NOT NULL,
  registration_num VARCHAR(25) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL
);

DROP TABLE users;

SELECT * FROM users;

CREATE TABLE products (
  product_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  product_name VARCHAR(255) NOT NULL,
  product_category VARCHAR(255) NOT NULL,
  owner_reg_num VARCHAR(25) NOT NULL
);

CREATE TABLE furnitures (
  furniture_id INT NOT NULL PRIMARY KEY,
  material VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  `condition` VARCHAR(255) NOT NULL,
  exchange_possible BOOLEAN NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT * FROM furnitures;

SELECT * FROM products;

DROP TABLE products;

CREATE TABLE computing_items (
  computing_id INT NOT NULL PRIMARY KEY,
  type VARCHAR(255) NOT NULL,
  ram VARCHAR(255) NOT NULL,
  `condition` VARCHAR(255) NOT NULL,
  exchange_possible BOOLEAN NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

DROP TABLE computing_items;

CREATE TABLE fashion_items (
  fashion_id INT NOT NULL PRIMARY KEY,
  gender VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  `condition` VARCHAR(255) NOT NULL,
  exchange_possible BOOLEAN NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE miscellaneous (
  miscellaneous_id INT NOT NULL PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  material VARCHAR(255) NOT NULL,
  `size` VARCHAR(255) NOT NULL,
  exchange_possible BOOLEAN NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE services (
  service_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL,
  company VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  exchange_possible BOOLEAN NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE books (
  book_id INT NOT NULL PRIMARY KEY,
  genre VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  `condition` VARCHAR(255) NOT NULL,
  exchange_possible BOOLEAN NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE health_beauty (
  health_beauty_id INT NOT NULL PRIMARY KEY,
  gender VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  `condition` VARCHAR(255) NOT NULL,
  exchange_possible BOOLEAN NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE electronics (
  electronic_id INT NOT NULL PRIMARY KEY,
  brand VARCHAR(255) NOT NULL,
  type VARCHAR(255) NOT NULL,
  `condition` VARCHAR(255) NOT NULL,
  exchange_possible BOOLEAN NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_path VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);